name: TruffleHog Scan

on: [push]

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TruffleHog
        run: |
          python3 -m pip install trufflehog

      - name: Run TruffleHog
        run: |
          trufflehog --regex .
